swagger: '2.0'
info:
  description: n1ce
  version: 1.0.0
  title: GAME
  contact:
    email: 732528169@qq.com
host: '192.168.0.123:3737'
tags:
  - name: sign
  - name: article
schemes:
  - http
paths:
  /ping:
    get:
      tags:
        - sign
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: sucess
  /signup:
    post:
      tags:
        - sign
      summary: 注册
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: data
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: sucess
  /signin:
    post:
      tags:
        - sign
      summary: 登陆获取token
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: data
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: sucess
  /article:
    post:
      tags:
        - article
      summary: 新建文章
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
        - in: body
          name: data
          required: true
          schema:
            $ref: '#/definitions/Article'
      responses:
        '200':
          description: sucess
definitions:
  User:
    type: object
    properties:
      account:
        type: string
      password:
        type: string
  Article:
    type: object
    properties:
      title:
        type: string
      content:
        type: string
      pics:
        type: array
        items:
          type: string
